/**
 * The corpus: everything the server knows about Perfect UI, generated by `scripts/build-corpus.ts`
 * from the library's documents at a tag and the published package's stylesheet. The server reads
 * nothing else.
 */
import { readFileSync } from "node:fs";
import { z } from "zod";

export const CORPUS_VERSION = "1.0.0";
export const DEFAULT_CORPUS = new URL(`../data/corpus-${CORPUS_VERSION}.json`, import.meta.url);

export const InstallSchema = z
  .object({
    package: z.string(),
    version: z.string(),
    npm: z.string().describe("npm command that installs the pinned version"),
    packageManagers: z.record(z.string(), z.string()).describe("install command per package manager, pinned"),
    cdn: z.object({ stylesheet: z.url(), script: z.url() }).strict(),
    imports: z.array(z.string()).describe("import statements from the installation document"),
    source: z.string().describe("library file the commands come from"),
  })
  .strict();

export const EntrySchema = z
  .object({
    slug: z.string().min(1),
    title: z.string().min(1),
    section: z.string().min(1),
    file: z.string().min(1).describe("path in the library repository"),
    description: z.string(),
    markdown: z.string().min(1),
    examples: z.array(z.string()).describe("the document's html code blocks"),
    classes: z.array(z.string()).describe("pui-* classes used in the examples"),
  })
  .strict();

export const CorpusSchema = z
  .object({
    version: z.string(),
    source: z
      .object({
        library: z.string().describe("the library ref the documents come from, or PERFECTUI_SOURCE"),
        package: z.string(),
        integrity: z.string().optional(),
      })
      .strict(),
    install: InstallSchema,
    components: z.array(EntrySchema).min(1),
    classes: z.array(z.string()).min(1).describe("every .pui-* selector of dist/perfectui.css"),
  })
  .strict();

export type Install = z.infer<typeof InstallSchema>;
export type Entry = z.infer<typeof EntrySchema>;
export type Corpus = z.infer<typeof CorpusSchema>;

/** Reads and validates a corpus file; a malformed file fails here, not inside a tool. */
export function loadCorpus(file: string | URL = DEFAULT_CORPUS): Corpus {
  const corpus = CorpusSchema.parse(JSON.parse(readFileSync(file, "utf8")));
  const slugs = new Set<string>();
  for (const entry of corpus.components) {
    if (slugs.has(entry.slug)) throw new Error(`corpus: the slug "${entry.slug}" appears twice`);
    slugs.add(entry.slug);
  }
  return corpus;
}
